### ISSUE TITLE
Review - 07/07/2024

### ISSUE THREAD

**Issue by xXcarlos117Xx2** [4GeeksAcademy/Simp-clic_Jaime#1]
Hacia ya tiempo que no hacia una de estas. Vamos al lio.

# Not that simple counter... O si
He visto algunos fallos en tu código. Créeme que entiendo perfectamente esas ganas de volar y de probar cosas nuevas, hacer los bonus y hacer volar tu imaginación con estos ejercicios, pero lo principal es que el código funcione con las instrucciones dadas y ya luego si tal que haga de más. Te lo he aprobado por que contar cuenta, pero empezando por que haces todo en el home.jsx y nada en el componente... Es algo que he visto en otros trabajos y no se de donde los sacais, pero es incorrecto.

### Incorrecta implementación de setInterval
En lugar de utilizar setTimeout para incrementar el contador cada segundo, debes utilizar setInterval para que el contador se actualice de forma continua. Es más, ni siquiera hemos dado el setTimeout, no se de donde lo has sacado.

### No se renderiza el componente cada segundo
Debido a la incorrecta implementación de setInterval, el componente no se renderiza cada segundo como se requiere.

### Uso innecesario de useState
El estado alert no es necesario, ya que se puede utilizar una variable local para almacenar el valor de la alerta. Además de ello, la alerta no funciona. Estas son las cosas que entiendo que quieres hacer cuando dejas volar tu imaginación, pero hay prioridades.

### Uso innecesario de useState
El estado isCountdown no es necesario, ya que se puede utilizar una variable local para almacenar el estado de la cuenta regresiva.

### Uso innecesario de section
Se utilizan varios elementos section para separar la interfaz de usuario, es algo que no hemos dado en HTML así que dudo de su procedencia. No es que este mal usado, pero me pregunto por que no usaste un div.

## Etc...
Hay muchos mas fallitos, como que los botones al pulsarlos van al revés. La directiva principal funciona, pero por favor, céntrate primero en las instrucciones principales y no uses tanta... "ayuda externa" 👀

**Comment by mecrophagus** [comment]
4Geeks, tiene un workshop, con el ejercicio. Quise probar mi conocimiento implementando otras "formas" pero como tu bien comentas, con las herramientas qué ya nos proporcionáis, deberíamos de hacerlo sin volvernos tan locos qué al final terminamos liándola peor. 

Me quedo con todo lo qué comentas, grande Carlos.
